### PR TITLE
Fix #13 `write': failed to allocate memory (NoMemoryError)

### LINKED ISSUE #13: failed to allocate memory (NoMemoryError)
I have a very large table in Postgres of size ~33GB.  After an hour of copying the data down, the memory runs out.  Seems to because `StringIO` is used with `Zlib::GzipWriter`:

```
$ postgres_to_redshift
Downloading scores
~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:92:in `write': failed to allocate memory (NoMemoryError)
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:92:in `write'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:92:in `block in copy_table'
        from /usr/local/share/ruby/gems/2.2/gems/pg-0.17.1/lib/pg/connection.rb:138:in `copy_data'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:90:in `copy_table'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:23:in `block in update_tables'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:20:in `each'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:20:in `update_tables'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/bin/postgres_to_redshift:5:in `<top (required)>'
        from ~/bin/postgres_to_redshift:23:in `load'
        from ~/bin/postgres_to_redshift:23:in `<main>'
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream was freed prematurely.
```

### PR DESCRIPTION
**Pull request by ashawley**
Using disk as an intermediary fixes the memory problem, but will affect runtime performance negatively and also means the application is dependent on the local filesystem, now.

### CODE REVIEW

File: lib/postgres_to_redshift.rb [hunk 1]
```diff
@@ -81,20 +81,24 @@ def bucket
...
+      source_connection.copy_data(copy_command) do
+        while row = source_connection.get_copy_data
+          zip.write(row)
+        end
       end
+      zip.finish
+      tmpfile.rewind
+      upload_table(table, tmpfile)
+    ensure
+      zip.close
```
Comment (toothrot) [inline lib/postgres_to_redshift.rb]: Good catch(es)!

**Comment by toothrot** [comment]
Nice! Our production database was *much* smaller when we designed this. 

This looks great! Out of curiosity, how long does this process take?

**Comment by toothrot** [comment]
You might want to check out implementing #7 for speedups on the import step.

File: lib/postgres_to_redshift.rb (hunk 1 above)
Comment (ashawley) [inline lib/postgres_to_redshift.rb]: Looks like I pushed my PR too soon. I should have written:

```
ensure
  zip.close unless zip.closed?
end
```
Otherwise, it causes:

```
~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:99:in `close': closed gzip stream (
Zlib::GzipFile::Error)
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:99:in `copy_table'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:23:in `block in update_tables'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:20:in `each'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/lib/postgres_to_redshift.rb:20:in `update_tables'
        from ~/.gem/ruby/2.2/gems/postgres_to_redshift-0.1.1/bin/postgres_to_redshift:5:in `<top (required)>'
        from ~/bin/postgres_to_redshift:23:in `load'
        from ~/bin/postgres_to_redshift:23:in `<main>'
```

Comment (toothrot) [inline lib/postgres_to_redshift.rb]: Thanks. I fixed this on master, and will push out a new gem version soon.

**Comment by ashawley** [comment]
The large tables are still giving me trouble, so I've only been able to transfer the smaller tables.  The smaller tables are about 1.1GB in total of compressed data (6GB uncompressed).  For both `StringIO` and for `Tempfile`, it is taking the same amount of time: ~35 minutes.  They are being copied from a db.t2.small RDS instance to a dc1.large Redshift cluster using a t2.small EC2 instance to run the gem.

**Comment by toothrot** [comment]
It might be worth figuring out how to extend this to copy tables in chunks. Because Redshift supports importing from a series of files, it might be worth only doing chunks of a table at a time:

Something like looping over:
```sql
COPY (SELECT #{table.columns_for_copy} FROM #{table.name} LIMIT 1000000 OFFSET 0)...
```

Though, that'd require a pretty significant rewrite of this gem. I'm not sure what else could help with that, though.
